<?php $this->placeholder('pageContent')->captureStart();?>
<div class="profile-sidebar">
	<!-- PORTLET MAIN -->
	<?=$this->partial('application/account/partial/profile.phtml')?>
	<!-- END PORTLET MAIN -->
</div>
<div class="profile-content">
	<div class="row">
		<div class="col-md-12">
			<div class="portlet light bordered">
				<div class="portlet-title tabbable-line">
					<div class="caption caption-md">
						<i class="icon-globe theme-font hide"></i> <span
							class="caption-subject font-blue-madison bold uppercase">账户信息</span>
					</div>
					<ul class="nav nav-tabs">
						<li class="active"><a href="#tab_1_1" data-toggle="tab">基本信息</a></li>
						<li><a href="#tab_1_2" data-toggle="tab">设置头像</a></li>
						<li><a href="#tab_1_3" data-toggle="tab">更改密码</a></li>
					</ul>
				</div>
				<div class="portlet-body">
					<div class="tab-content">
						<!-- PERSONAL INFO TAB -->
						<?=$this->partial('application/account/partial/tab-person-info.phtml')?>
						<!-- END PERSONAL INFO TAB -->
						<!-- CHANGE AVATAR TAB -->
						<?=$this->partial('application/account/partial/tab-avatar.phtml')?>
						<!-- END CHANGE AVATAR TAB -->
						<!-- CHANGE PASSWORD TAB -->
						<?=$this->partial('application/account/partial/tab-password.phtml')?>
						<!-- END CHANGE PASSWORD TAB -->
						<!-- PRIVACY SETTINGS TAB -->
						<?=$this->partial('application/account/partial/tab-oauth.phtml')?>
						<!-- END PRIVACY SETTINGS TAB -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->placeholder('pageContent')->captureEnd() ?>
<?=$this->partial('partial/application/page/page/basic-page.phtml', [
    'pageGroup' => 'Account',
    'pageName' => 'IndexPage',
    'pageTitle' => '个人中心',
    'pageContent' => $this->placeholder('pageContent')
])?>