<?php 
$identity = $this->identity();
$avatar   = $identity->avatar;
?>
<div class="tab-pane" id="tab_1_2">
	<p>请上传个人头像，(可以是png jpg jpeg等图片格式，2M以内)</p>
	<p>最好是300 x 300 像素</p>
	<div 
	class="thumbnail dropzone-previews" >
	<a href="javascript:;" class="btn red btn-outline upload-file">选择文件</a>
	<img src="<?=$avatar?>" alt="avatar" id="img_avatar" style=" margin: 10px 0 0 0 ">
	</div>
	<div class="dropzone hide"></div>
</div>