<?php 
$type = $this->type;
$desc = $this->desc;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <?= $this->headTitle($type)->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <link rel="shortcut icon" href="/_application/favicon.ico" />
        <link href="/_application/css/error.css" rel="stylesheet">
        <?=$this->partial('layout/application/partial/css.phtml')?>
     </head>
    <!-- END HEAD -->

    <body class=" page-500-full-page">
        <div class="row">
            <div class="col-md-12 page-500">
                <div class=" number font-red"> <?=$type?> </div>
                <div class=" details">
                    <h3><?=$desc?></h3>
                    <p>
                        <a href="javascript:history.back()" class="btn red btn-outline"> 返回上一页 </a>
                        <br> </p>
                </div>
            </div>
        </div>
    </body>
</html>
