<?php 
$pageGroup = $this->pageGroup;
$pageName  = $this->pageName;
$pageTitle = $this->pageTitle;
$buttons   = $this->buttons;
$table     = $this->table;
$tableToolbar= $this->tableToolbar;
?>
<?php $this->placeholder('pageContent')->captureStart();?>
<div class="portlet light portlet-fit portlet-datatable bordered">
	<div class="portlet-title">
        <div class="caption font-dark">
            <i class="icon-list font-dark"></i>
            <span class="caption-subject bold uppercase">列表</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" data-original-title="" title=""> </a>
            <a href="" class="fullscreen" data-original-title="" title=""> </a>
        </div>
    </div>
    
	<div class="portlet-body">
		<?php if ($tableToolbar !== false):?>
		<div class="table-toolbar">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="btn-group">
                    	<?=$buttons?>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6">
                    <div class="btn-group pull-right">
                        <button 
                        class="btn green  btn-outline dropdown-toggle" 
                        data-toggle="dropdown" 
                        aria-expanded="false">导出 <i class="fa fa-angle-down"></i></button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-print"></i> 打印 </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-file-pdf-o"></i> 保存为PDF </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="fa fa-file-excel-o"></i> 保存为EXCEL </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?php endif;?>
        <div class="table-responsive table-container">
        <?=$table?>
        <div class="pagination-control"></div>
        </div>
	</div>
</div>
<?php $this->placeholder('pageContent')->captureEnd() ?>
<?= $this->partial('partial/application/page/page/basic-page.phtml', [
    'pageGroup' => $this->pageGroup,
    'pageName'  => $this->pageName,
    'pageTitle' => $this->pageTitle,
    'pageContent'=> $this->placeholder('pageContent'),
])?>
