<?php 
use Api\Repository\Table\User;

$users = $this->User()->findAll();

?>
<?php $this->placeholder('table')->captureStart();?>
<table
	class="table table-striped table-bordered table-hover table-checkable order-column"
	id="table_user">
	<thead>
		<tr>
			<th>
                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                    <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                    <span></span>
                </label>
            </th>
			<td>用户名</td>
			<td>真实姓名</td>
			<td>真实姓名</td>
		</tr>
	</thead>
</table>
<?php $this->placeholder('table')->captureEnd() ?>
<?= $this->partial('partial/application/page/page/table-page.phtml', [
    'pageGroup' => 'User',
    'pageName'  => 'UserListPage',
    'pageTitle' => '用户管理',
    'table'=> $this->placeholder('table'),
])?>
