<?php $this->placeholder('buttons')->captureStart();?>
<?=$this->partial('partial/application/button/fill/add.phtml')?>
<?php $this->placeholder('buttons')->captureEnd() ?>

<?php $this->placeholder('table')->captureStart();?>
<div class="table-responsive table-container">
	<table
	class="table table-striped table-bordered table-hover table-checkable "
	id="table_user">
	<thead>
		<tr>
			<th class="th_5">
				<label
					class="mt-checkbox mt-checkbox-single mt-checkbox-outline"> <input
					type="checkbox" class="group-checkable" data-set="" /> <span></span>
				</label>
			</th>
			<th class="th_15">用户名</th>
			<th class="th_15">真实姓名</th>
			<th class="th_15">电话</th>
			<th class="column_status">状态</th>
			<th>角色</th>
			<th>操作</th>
		</tr>
		<?=$this->partial('application/user/partial/tr-search.phtml')?>
	</thead>
	<tbody>
    </tbody>
</table>
</div>
<?php $this->placeholder('table')->captureEnd() ?>
<?= $this->partial('partial/application/page/page/table-page.phtml', [
    'pageGroup' => 'User',
    'pageName'  => 'UserListPage',
    'pageTitle' => '用户管理',
    'paginator' => $users,
    'buttons'   => $this->placeholder('buttons'),
    'table'     => $this->placeholder('table'),
])?>
