<!-- lib -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet" >
<!-- font -->
<link href="/_application/css/font-awesome.min.css" rel="stylesheet">
<link href="/_application/css/simple-line-icons.css" rel="stylesheet">
<!-- nprogress -->
<link href="https://cdn.bootcss.com/nprogress/0.2.0/nprogress.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css" rel="stylesheet">
<!-- bootstrap -->
<link href="https://cdn.bootcss.com/jquery.bootstrapvalidator/0.5.3/css/bootstrapValidator.min.css" rel="stylesheet">
<!-- select2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.1/css/select2.min.css" rel="stylesheet">
<!-- suctome -->
<link href="/_application/css/layout.css" rel="stylesheet">
<link href="/_application/css/themes/light.css" rel="stylesheet">
<link href="/_application/css/components.css" rel="stylesheet">
<link href="/_application/css/custom.css" rel="stylesheet">

<!-- <link href="https://colorlib.com/polygon/vendors/animate.css/animate.min.css" rel="stylesheet"> -->
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.css" rel="stylesheet"> -->
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet"> -->
<!-- <link href="https://cdn.bootcss.com/bootstrap-daterangepicker/3.0.3/daterangepicker.min.css" rel="stylesheet"> -->