<!-- 
引入最基本的css文件 
其他如select2用的css时通过require一起引入
-->
<!-- lib -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet" >
<!-- font -->
<link href="/_application/css/font-awesome.min.css" rel="stylesheet">
<link href="/_application/css/simple-line-icons.css" rel="stylesheet">
<!-- suctome -->
<link href="/_application/css/layout.css" rel="stylesheet">
<link href="/_application/css/themes/light.css" rel="stylesheet">
<link href="/_application/css/components.css" rel="stylesheet">
<link href="/_application/css/custom.css" rel="stylesheet">
<!-- nprogress -->
<link href="https://cdn.bootcss.com/nprogress/0.2.0/nprogress.min.css" rel="stylesheet">
