<?php
use Api\Service\WebsiteManager;

$title  = $this->Website()->getWebsiteConfig(WebsiteManager::WEBSITE_ADMIN, 'title');
$ico    = $this->Website()->getWebsiteConfig(WebsiteManager::WEBSITE_ADMIN, 'ico');
?>
<meta charset="utf-8" />
<?= $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false) ?>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport" />
<meta content="" name="description" />
<meta content="" name="author" />
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link rel="shortcut icon" href="<?=$ico?>" />
<?=$this->partial('layout/application/partial/css.phtml')?>