<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner ">
		<!-- BEGIN LOGO -->
		<?=$this->partial('layout/application/partial/top-logo.phtml')?>
		<!-- END LOGO -->

		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler"
			data-toggle="collapse" data-target=".navbar-collapse"> </a>

		<!-- BEGIN PAGE ACTIONS -->
		<?=$this->partial('layout/application/partial/top-action.phtml')?>
		<!-- END PAGE ACTIONS -->

		<div class="page-top">
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">
					<li class="separator hide"></li>
					<li class="separator hide"></li>
					<li class="separator hide"></li>
					<?=$this->partial('layout/application/partial/top-nav-profole.phtml')?>
				</ul>
			</div>
		</div>
		
	</div>
</div>