<?php 
$query = $this->query;
$action = $this->action;
$action = $action ?? 'index';
?>
<div class="" style="width: 100%">
	<div class="pull-left">
		<div 
		class="paginator-detail" 
		>当前 <?=$this->currentItemCount?> 条数据，共  <?=$this->totalItemCount?> 条数据</div>
	</div>
	<div class="pull-right">
		<div class="dataTables_paginate paging_simple_numbers"
			aria-label="Page navigation">
			<ul class="pagination" style="margin: auto">
            <!-- 上一页 -->
            <?php if (isset($this->previous)): ?>
                <li class="">
                    <a 
                    href="<?= $this->url($this->route,['action'=>$action, 'page'=>$page],['query'=>$query],true); ?>"
                    >上一页</a>
                </li> 
            <?php else: ?>
           	 	<li class="disabled"><a href="javascrip:;">上一页</a></li>
            <?php endif; ?>
            
            <!-- 页码 -->
            <?php foreach ($this->pagesInRange as $page): ?>
				<?php if ($page != $this->current): ?>
                    <li class="">
                    	<a href="<?= 
                    	$this->url(
                    	    'user', 
                    	    ['action'=>'test', 'page'=>$page], 
                    	    ['query'=>$query], false); ?>"
                    	><?= $page; ?></a>
                    </li>
				<?php else: ?>
				    <!-- 当前页面 -->
					<li class="disabled"><a><?= $page; ?></a></li>
				<?php endif; ?>
			<?php endforeach; ?>
            <!-- 下一页 -->
			<?php if (isset($this->next)): ?>
				<li class="">
					<a href="<?= 
					$this->url(
					    $this->route,
					    ['page'=>$page, 'action'=>$action],
					    ['query'=>$query],
                    	    true); ?>"
					>
						<span>下一页</span>
					</a>
				</li>	
			<?php else: ?>
			<li class="disabled"><a href="javascrip:;">下一页</a></li>
			<?php endif; ?>
        </ul>
		</div>
	</div>
</div>
